### ISSUE TITLE
Name of this action; further split?

### ISSUE THREAD

**Issue by fingolfin** [gap-actions/process-coverage#2]
The repository is named `coverage-for-codecov`

The README.md says `codecov-coverage-for-packages`

Also, I wonder if we should further change this to drop the coverage uploading, instead recommending that packages use e.g. https://github.com/marketplace/actions/codecov for uploading. Then if people want to use another service instead (Coveralls, Codacy, ...) they can.

Then the name for this action could just be `gather-coverage` or `process-coverage` ...

Thoughts? @gap-actions/write-access

**Comment by wilfwilson** [comment]
No strong feelings on my part; your "I wonder if" proposals sound like a decent idea.

**Comment by ssiccha** [comment]
Fixed by 2edaf6d. That commit is now tagged as `v2`.
